#!/usr/bin/env bash
cd JOKER                             ••
echo -e "\e[33m          ____  _      _ _ _ ____ ______  _____  \e[0m"
echo -e "\e[33m         / ___ | \\   | | | |    |______||     |\e[0m"
echo -e "\e[33m         \___ \| •\\  | | | |____||__    |_____|\e[0m"
echo -e "\e[33m          ___) | | \\ | | | |    ||__|__ ||\\     \e[0m"
echo -e "\e[33m         |____/|_|  \\|_|_|_|    |______||| \\   \e[0m"
while(true) do
lua start.lua 
done